### ISSUE TITLE
Release and Presentation

### ISSUE THREAD

**Issue by sameo** [virt-do/cloudlet#48]
@virt-do/virt-do-2024  I see some good progress has been made, and I think it's time to make your first release and present it to your favorite teacher.

Would you be available for doing that presentation on May 31st?

**Comment by thomas-mauran** [comment]
Hello @sameo we are free the entire day, at what time would you like us to present (so we can block the slot in the planning) ?

**Comment by sameo** [comment]
@thomas-mauran May 31st, at 2pm?

**Comment by thomas-mauran** [comment]
sounds good, contacting Eleonora to confirm the slot @sameo

**Comment by thomas-mauran** [comment]
Confirmation, it has been added to our planning see you there @sameo

**Comment by sameo** [comment]
Thanks and noted! Closing this issue now.
